<a href="https://colab.research.google.com/github/AleksandraJuras2000/Kurs_Udemi/blob/main/01_wprowadzenie/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello Colab')

Hello Colab


## NumPy - Intro
NumPy, czyli Numerical Python, to biblioteka programistyczna w języku Python, która dostarcza wsparcie dla efektywnych operacji numerycznych, zwłaszcza na dużych tablicach i macierzach danych. Jest jednym z podstawowych narzędzi w dziedzinie naukowych obliczeń i analizy danych w języku Python.



Główne cechy i funkcje biblioteki NumPy:

### Tablice wielowymiarowe:
 NumPy wprowadza nowy typ danych, znany jako "array" (tablica), który pozwala na przechowywanie i operowanie danymi wielowymiarowymi. Tablice w NumPy są bardziej wydajne niż standardowe listy w Pythonie i pozwalają na efektywne wykonywanie operacji matematycznych i statystycznych na danych.

### Efektywne operacje numeryczne:
 NumPy dostarcza wiele wbudowanych funkcji i operacji, takich jak dodawanie, mnożenie, podnoszenie do potęgi, funkcje trygonometryczne itp., które działają efektywnie na dużych zbiorach danych.

### Broadcasting:
NumPy umożliwia wykonywanie operacji na tablicach o różnych kształtach, co jest nazywane "broadcasting". Dzięki temu można wygodnie operować na danych o różnych wymiarach, a NumPy automatycznie dostosowuje kształt tablic.

### Indeksowanie i wycinanie:
NumPy oferuje zaawansowane możliwości indeksowania i wycinania danych z tablic, co pozwala na dostęp do konkretnych elementów lub podtablic z dużą precyzją.

### Losowanie liczb:
 Biblioteka umożliwia generowanie losowych liczb o różnych rozkładach, co jest przydatne w symulacjach i analizach statystycznych.

### Integracja z innymi bibliotekami:
NumPy jest często używany w połączeniu z innymi bibliotekami do naukowych obliczeń i analizy danych, takimi jak SciPy, pandas, matplotlib i scikit-learn.

### Obsługa danych brakujących:
NumPy ma wbudowane funkcje do pracy z danymi brakującymi, co jest istotne w analizie danych.

### Obsługa danych binarnych:
Możesz używać NumPy do operacji na danych binarnych, takich jak obrazy, dźwięk czy pliki binarne.



NumPy jest nieodzowną biblioteką w ekosystemie naukowych obliczeń w języku Python. Dzięki niej programiści i naukowcy danych mogą wygodnie manipulować dużymi zbiorami danych numerycznych i wykonywać zaawansowane operacje matematyczne. W połączeniu z innymi narzędziami do analizy danych i wizualizacji, NumPy stanowi solidną podstawę dla wielu projektów związanych z naukowymi obliczeniami i analizą danych.

In [3]:
import numpy as np

In [2]:
np.__version__  # w kursie używana wersja to 1.17.4

'1.26.4'

In [4]:
print(dir(np))  # tu sa wszystkie elementy które sa do użycia w bibliotece

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [ ]:
help(np.array) # cala instrukcja do array

### 1D ARRAY

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim # wymiar tablicy

1

In [10]:
x.shape #wyswietlenie za pomoca tupli

(2,)

In [11]:
x.size #liczba elementow w tablicy

2

In [12]:
x.dtype # typ danych wewnatrz tablicy

dtype('int64')

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

### 2D ARRAY

In [17]:
x = np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [21]:
x = np.array([[1, 2, 4], [4, 2, 3]])
print(x)

[[1 2 4]
 [4 2 3]]


In [22]:
x.shape

(2, 3)

### 3D ARRAY

In [26]:
# przechowuje dany tak jak np. obrazy
x = np.array(
    [[[4, 3, 2],
       [3, 4, 1]],

     [[4, 1, 3],
     [4, 2, 1]],

     [[3, 2, 1],
     [4, 3, 2 ]]]
)
x

array([[[4, 3, 2],
        [3, 4, 1]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [27]:
x.ndim

3

In [28]:
x.shape # 3 tablice, dwa wiersze i 3 kolumny

(3, 2, 3)

### Typy Danaych

In [29]:
A = np.array([1, 3, 4], dtype='float')

In [30]:
A.dtype

dtype('float64')

In [31]:
A

array([1., 3., 4.])

In [33]:
A = np.array([1, 3, 4], dtype='complex')
A

array([1.+0.j, 3.+0.j, 4.+0.j])

In [34]:
A = np.array([1.0, 3.6, 4.5], dtype='int')
A.dtype

dtype('int64')

In [35]:
A #nie zaokrągla

array([1, 3, 4])

In [36]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [41]:
A = np.array([24, 120, 230]).astype(np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230]).astype(np.uint8) # uint to wartosci od 0 do 255 tak jak opisujemy obrazy
A.dtype

### TWORZENIE TABLIC

In [42]:
np.zeros(shape = (4, 10)) #domyslym typem jak typ float

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.zeros(shape = (4, 10)).astype(int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [44]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.full(shape = (3, 3), fill_value=4, dtype = 'int') # maciez wypelniona jakas konkretna wartoscia

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
np.arange(start = 5, stop = 10)

array([5, 6, 7, 8, 9])

In [50]:
np.arange(start = 10, stop = 100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
np.arange(start = 100, stop = 10, step = -10) # tu idzie w druga strone pamietac o kroku ujemnym

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [52]:
np.arange(start = 0, stop = 1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [53]:
np.linspace(start = 0, stop = 1, num = 10) #parametr num okresla liczbe elementow rowno rozlozonych w tym przedziale

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [56]:
A = np.arange(15)

In [57]:
A.reshape((3, 5)) # jesli uzywamy rehape to tak aby iloczyn dawal nam ilosc elementow

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
A.reshape((3, -1)) # chcemy miec 3 wiersze i nich mi python dobierze odpowiedzia liczbe kolumn ===> -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### PODSTAWOWE OPERACJE NA TABLICACH

In [59]:
A = np.array ([3, 2, 4, 2])
B = np.array ([6, -7, 3, 8])
print(A)
print(B)

[3 2 4 2]
[ 6 -7  3  8]


In [60]:
#rozmiar musi sie zgadzac
A + B

array([ 9, -5,  7, 10])

In [61]:
A - B

array([-3,  9,  1, -6])

In [62]:
A * B

array([ 18, -14,  12,  16])

In [63]:
A / B # tu aby nasza tablica przez ktoa dzielimy nie zawierala 0

array([ 0.5       , -0.28571429,  1.33333333,  0.25      ])

In [68]:
np.add(A, B)

array([ 9, -5,  7, 10])

In [69]:
np.subtract(A, B)

array([-3,  9,  1, -6])

In [70]:
np.multiply(A, B)

array([ 18, -14,  12,  16])

In [71]:
np.divide(A, B)

array([ 0.5       , -0.28571429,  1.33333333,  0.25      ])

In [64]:
# dodawanie stałej
A + 3

array([6, 5, 7, 5])

In [65]:
A - 9

array([-6, -7, -5, -7])

In [66]:
2 * A

array([6, 4, 8, 4])

In [67]:
A + 3 * B

array([ 21, -19,  13,  26])

In [74]:
#mnozenie macierzowe
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [76]:
X * Y # w takim przypadku bedzie mnożenie po elemencie, NIE JEST TO MNOŻENIE MACIERZY

array([[6, 0],
       [2, 0]])

In [75]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [77]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [78]:
Y.dot(X) # MNOŻENIE MACIERZY NIE JEST PRZEMIENNE

array([[ 6, 18],
       [-5, -3]])

In [79]:
X @ Y # to tez jest mnożenie macierzy

array([[  3,   6],
       [-12,   0]])

### GENEROWANIE LICZB PSEUDOLOSOWYCH

In [80]:
np.random.seed(0) # ustawiamy ziarno losowania aby za kazdym razem miec ten sam wynik losowania

In [81]:
np.random.randn() #losowa wartosc z rozkladu normalnego

1.764052345967664

In [82]:
np.random.randn(10) # wiekszosc liczb w przedziale -3 do 3

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [83]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [84]:
np.random.rand() #zwraca z przedzialu 0 do 1

0.1965823616800535

In [85]:
np.random.rand(10, 2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [86]:
np.random.randint(10)  # zwraca liczbe calkowita mniejsza niz 10 i liczbe nieujemna, losowo

1

In [90]:
np.random.randint(low=10, high = 101, size = 10) #losowa liczba dwucyfrowa

array([51, 68, 75, 46, 20, 96, 53, 21, 12, 61])

In [99]:
np.random.choice([4, 2, 1, 3, 7, 8]) # zwraca losowy element z listy

3

In [100]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [101]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.random.shuffle(data) #od razu zmienia postac naszych danych, np. w pandas trzebaby było zapisac do nowej zmiennej

In [103]:
data

array([4, 0, 1, 7, 6, 3, 2, 5, 9, 8])

### PODSTAWOWE FUNKCJE

In [104]:
np.exp(1)  # popularna funkcja w sieciach neuronowych

2.718281828459045

In [106]:
np.sqrt(9) # zwraca zawsze w typieu float

3.0

In [107]:
np.all([2, 3, 1]) # jeseli kazda wartosc zwroci True to zwroci True a jesli chociaz jedno zwroci False to calosc zwroci False

True

In [108]:
np.any([0, 0, 0]) # Jesli sa jakiekolwiek prawdy to zroci True, jesli wszytko to False to zróci False

False

In [110]:
bool(9.9) # tylko w przypadku zera zwraca wartosc false

True

In [112]:
A = np.random.rand(5)
A

array([0.22308163, 0.95274901, 0.44712538, 0.84640867, 0.69947928])

In [113]:
# uzyj funkcji ktora zwroci indeks z najwieksza wartoscia
np.argmax(A) # zwroci indeks

1

In [114]:
A[np.argmax(A)]

0.952749011516985

In [115]:
np.argmin(A)

0

In [117]:
np.argsort(A) # sortuje elementy od najmniejszego do najwiekszego

array([0, 2, 4, 3, 1])

In [118]:
np.max(A)

0.952749011516985

In [119]:
np.min(A)

0.2230816326406183

In [120]:
np.mean(A)

0.6337687941127725

In [121]:
np.median(A)

0.6994792753175043

In [122]:
np.std(A)

0.26637630279339825

### INDEKSOWANIE, WYCINANIE

In [123]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [126]:
# A[idx], A[start:stop], A[:stop], A[start:]
A[2]
A[2:]
A[:2]

array([0, 1])

In [127]:
A[[0, 2]] # wycinamy indeks 0 oraz 2

array([0, 2])

In [128]:
A[-1] # zwraca ostatni element

19

In [129]:
A[10:15]

array([10, 11, 12, 13, 14])

In [132]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [134]:
A[:, 0] #kolumna 0

array([ 0,  5, 10, 15])

In [135]:
A[:, -1] #ostatnia kolumna

array([ 4,  9, 14, 19])

In [137]:
A[1, 3]

8

In [140]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [142]:
A[1, 2]  = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### ITERACJA PO TABLICACH

In [4]:
A = np.arange(20)

In [7]:
A = A.reshape(4,5)

In [9]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [11]:
for row in A:
  print(row[1])

1
6
11
16


In [12]:
for row in A:
  print(row[:2])

[0 1]
[5 6]
[10 11]
[15 16]


In [13]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### ZMIANA ROZMIARU TABLIC

In [14]:
A.shape

(4, 5)

In [15]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
A.ravel() #wypłaszcza nasze dane do postaci 1 wymiarowej

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
A.T  # transponowana tablica

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### MASKI LOGICZNE

In [19]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [20]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
A[A > 0 ]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [23]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [25]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])