<a href="https://colab.research.google.com/github/AleksandraJuras2000/Kurs_Udemi/blob/main/07_sieci_neuronowe/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.17.1'

## Wprowadzenie pierwszy model

Model sekwencyjny to nic innego jak liniowy stos warstw

In [7]:
# musimy utworzyc instancje
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

<Sequential name=sequential_1, built=False>


Podstawowym elementem składowym modelu sa warstwy. Aby dodać najbardziej standardową warstwe - warstwę gęsto poączoną należy użyć warstwy Dense. Aby dodać warstwę do modelu należy użyć metody .add()

In [8]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))   # units to liczbaneuronów w warstwie, input shape to 10 zmiennych opisujących naszą zmeinna docelową
# jesli mamy obrazy to musimy podać rozmiar obrazu czyli input shape = 28x28

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Wyświetlanie podsumowania modelu: metoda.summary()

In [9]:
model.summary()  # liczba parametrów to (input_shape + 1) * liczba neuronów w naszym przypadku Param to 44, tyle wag do przetrenowania

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 4)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

Dodawanie kolejnej warstwy

In [10]:
model.add(Dense(units=2))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

## Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn.

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

In [18]:
# zaimportujemy na początek najbardziej podstawową funkcje aktywacji
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()   # jest to domyślna funkcja liniowa, zwraca nam tą samą wattość

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [19]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [20]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()
# 1/(1+e^-x)

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [22]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [23]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()
# zeruje wartości ujemne, a war dod zostawia bez zmian

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [24]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [25]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()
# zwraca war od -1 do 1aa

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [26]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [27]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))  # tu mamy jedna kalse do przewidzenie czylui tzw binarny
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

## Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:

* rodzaj optymalizatora (Keras - Optymalizatory)
* funkcję straty (Keras - Funkcje Straty)
* metryki, które będziemy obserwować podczas trenowania sieci (Keras - Metryki)

In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])               #

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])               #

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')                         #

## Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:

* epochs - krotność przejścia danych przez sieć w procesie uczenia   (jesli 5 to 5 razy nasze dane przeszly przez ten proces uczenenia im wiecej epok tym proces bedzie dłuższy)
* batch_size - rozmiar wsadu po którym następuje aktualizacja wag   (domyślnie 32)  
* validation_split - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny   (jezeli chcemy podczas trenowania wydzielic jakis zbiór do walidacji mozemy przekazac ten parametr jako część tych danych żęy był potraktowany jako zbiór walidacyjny, polene wydzielic!!!, jesli 0,2 --> to 20% danych na zbiór walidacyjny)
* validation_data - (x_val, y_val) - dane wykorzystane do walidacji modelu     ( tuple )

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

## Przykład - klasa binarna

In [28]:
data = np.random.randn(10000, 150)   #10000 to liczb awierszy 150 to liczba kolumn
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [31]:
type(data)

numpy.ndarray

In [29]:
data[:3]   # wyświetlamy sobie 3 takie tuple

array([[-1.48214532e+00, -8.29144241e-01,  9.03138521e-01,
         3.47925145e+00,  1.97677250e+00,  1.45925655e+00,
        -5.38111332e-01,  1.30929005e+00,  2.29737364e-01,
        -3.12864071e-01,  1.95836307e+00, -5.43436082e-02,
         1.47113609e+00,  7.46108279e-01, -3.21913570e-01,
         3.37925423e-02,  2.21551272e-01,  3.53310468e-01,
        -1.27972823e-01,  7.39368395e-01,  4.95519312e-01,
         1.22912742e+00,  4.73533678e-01, -1.54329502e-01,
        -1.14051914e+00,  2.61923578e+00,  1.25988747e+00,
         7.94385774e-01,  5.09256570e-01,  6.78070694e-01,
        -6.28576025e-01, -1.74291867e+00, -1.56804208e+00,
         9.94789141e-01,  1.62655263e+00, -7.86273311e-01,
         2.92739990e-01,  1.30960394e+00,  4.30297322e-02,
         1.04012053e+00, -6.28126644e-01, -4.84277294e-01,
         1.18223168e+00, -1.45858101e+00,  1.50434120e+00,
         1.62284942e+00,  7.07252925e-01,  2.96581130e-01,
         4.18823167e-01, -1.04782679e+00, -2.96754405e+0

In [30]:
labels[:10]

array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1]])

In [32]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))   # jesli model jest klasyfikacji binarnej na końcu mamy jeden neuron czyli klasa albo 1 albo 0
# sigmoid zwraca prawdopodobieństwo dostania sie do tych dwóch klas

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Epoch 1/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5003 - loss: 0.7957
Epoch 2/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5500 - loss: 0.6898
Epoch 3/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5805 - loss: 0.6734
Epoch 4/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6013 - loss: 0.6614
Epoch 5/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6380 - loss: 0.6426
Epoch 6/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6470 - loss: 0.6332
Epoch 7/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6642 - loss: 0.6211
Epoch 8/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6823 - loss: 0.6032
Epoch 9/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6960 - loss: 0.5925
Epoch 10/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7056 - loss: 0.5810
Epoch 11/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7204 - loss: 0.5622
Epoch 12/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step

In [33]:
#jak dodawać parametry np. batch size
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5023 - loss: 0.7629
Epoch 2/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5341 - loss: 0.6960
Epoch 3/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5619 - loss: 0.6819
Epoch 4/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5955 - loss: 0.6675
Epoch 5/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6047 - loss: 0.6591
Epoch 6/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6351 - loss: 0.6491
Epoch 7/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6409 - loss: 0.6397
Epoch 8/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6632 - loss: 0.6301
Epoch 9/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6692 - loss: 0.6209
Epoch 10/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6920 - loss: 0.6043
Epoch 11/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6964 - loss: 0.5941
Epoch 12/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy

In [34]:
#jak dodawać parametry np. batch size
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)
#

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5125 - loss: 0.7869 - val_accuracy: 0.4895 - val_loss: 0.7427
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5480 - loss: 0.6950 - val_accuracy: 0.4920 - val_loss: 0.7386
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5868 - loss: 0.6713 - val_accuracy: 0.4885 - val_loss: 0.7418
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6142 - loss: 0.6530 - val_accuracy: 0.4775 - val_loss: 0.7453
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6461 - loss: 0.6325 - val_accuracy: 0.4900 - val_loss: 0.7439
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6690 - loss: 0.6133 - val_accuracy: 0.4845 - val_loss: 0.7513
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6927 - loss: 0.6028 - val_accuracy: 0.4855 - val_loss: 0.7566
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7043 - loss: 0.5850 - val_accuracy: 0.4880 - val_

In [38]:
from re import VERBOSE
#jak dodawać parametry np. batch size
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=64, validation_split=0.2, verbose=0) # verbose nie wyświetla tekstu

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



In [40]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [43]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose = 1)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5086 - loss: 0.7714 - val_accuracy: 0.4850 - val_loss: 0.7365
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5680 - loss: 0.6863 - val_accuracy: 0.4760 - val_loss: 0.7349
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6038 - loss: 0.6664 - val_accuracy: 0.4800 - val_loss: 0.7389
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6331 - loss: 0.6487 - val_accuracy: 0.4695 - val_loss: 0.7398
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6527 - loss: 0.6280 - val_accuracy: 0.4795 - val_loss: 0.7446
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6600 - loss: 0.6230 - val_accuracy: 0.4905 - val_loss: 0.7493
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6849 - loss: 0.6024 - val_accuracy: 0.4815 - val_loss: 0.7588
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7034 - loss: 0.5854 - val_accuracy: 0.4890 - val_

In [44]:
# jak dokonać predykcji próbek na podstawoie naszego modelu
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))


In [45]:
model.predict(test_data)
#dostajemy prawdopodobieństwo danej klasy jesli jest blizej 0 to jest 0 a blizej 1 jest 1

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[0.84394443],
       [0.7021321 ],
       [0.15549658],
       [0.12554367],
       [0.2165078 ]], dtype=float32)

In [48]:
# Konwersja na klasy (0 lub 1)
probabilities = model.predict(test_data)
classes = (probabilities > 0.5).astype("int")
print(classes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[1]
 [1]
 [0]
 [0]
 [0]]


## Klasyfikacja wieloklasowa

In [49]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))


print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [50]:
labels[:10]  # mamy klasy od 0 do 9

array([[0],
       [3],
       [5],
       [6],
       [0],
       [0],
       [7],
       [0],
       [2],
       [5]])

In [52]:
from tensorflow.keras.utils import to_categorical

labels = to_categorical(labels, num_classes=10)
labels
# przypoisujemy jedynke do tej kolumny gdzie prawdopodobiemnstwo jest najwieksze

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [53]:
labels[1]  # 3

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [56]:
model = Sequential()
model.add(Dense(units=32, activation = 'relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))  # dajemy tyle neuronów ile mamy klas czyli 10 nastepnie funkcje która zwraca podobieństwa poszczególnej klasy

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1017 - loss: 2.3369 - val_accuracy: 0.0975 - val_loss: 2.3053
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1078 - loss: 2.3017 - val_accuracy: 0.0870 - val_loss: 2.3055
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1153 - loss: 2.3006 - val_accuracy: 0.0995 - val_loss: 2.3058
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1131 - loss: 2.2992 - val_accuracy: 0.1025 - val_loss: 2.3053
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1176 - loss: 2.2978 - val_accuracy: 0.1040 - val_loss: 2.3091
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1182 - loss: 2.2947 - val_accuracy: 0.1030 - val_loss: 2.3080
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1127 - loss: 2.2937 - val_accuracy: 0.1060 - val_loss: 2.3098
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1206 - loss: 2.2910 - val_accuracy: 0.

In [57]:
test_data = np.random.random((10, 150))

model.predict(test_data)  # zwraca prawd. poszczególnej klasy, tam gdzei prawd. jest maksymalne to bedzie nasza etykieta

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[0.08824801, 0.17931557, 0.07595275, 0.11817975, 0.14910401,
        0.05149554, 0.04873016, 0.11679788, 0.09175353, 0.08042275],
       [0.0974275 , 0.11942067, 0.07090302, 0.09499621, 0.09072097,
        0.09710889, 0.09519874, 0.11242869, 0.12007864, 0.10171672],
       [0.06393496, 0.081737  , 0.07804717, 0.08522761, 0.05631685,
        0.07277126, 0.12832989, 0.10958774, 0.19554694, 0.12850057],
       [0.10832583, 0.08492957, 0.10902641, 0.10124894, 0.09623728,
        0.11887907, 0.08746161, 0.08834571, 0.10482604, 0.10071954],
       [0.10460252, 0.08467414, 0.06321214, 0.1581513 , 0.16272153,
        0.0808583 , 0.06071662, 0.0898705 , 0.07792622, 0.11726674],
       [0.07662515, 0.17528965, 0.09246902, 0.10734582, 0.1107564 ,
        0.0523654 , 0.05443678, 0.10104015, 0.15909053, 0.07058104],
       [0.07564855, 0.1492444 , 0.07068118, 0.11880127, 0.1711298 ,
        0.06571461, 0.05213374, 0.11878252, 0.09067737, 0.08718653],
       [0.0812316 , 0.10880651, 0.1008114

In [62]:
probabilities = model.predict(test_data)

# Przewidywanie klas (największe prawdopodobieństwo w każdym wierszu)
predicted_classes = np.argmax(probabilities, axis=1)

print(predicted_classes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[1 8 8 5 4 1 4 8 6 4]


##Dobre dopasowanie funkcji ma duze znaczenie!!!!!!!!!!!!!!!!!
* SIGMOID W KLASYFIKACJI BINARNEJ
* SOFTMAX W KLASYFIKACJI WIELOKLASOWEJ

## Funkcja straty też musi być odpowiednia
* BINARY CROSSENTROPY PRZY BINARNEJ
* CATEGORICAL CROSSENTROPY PRZY WIELU KLASACH

## Regresja

In [73]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [74]:
labels[:10]

array([23.09338825, 29.34432528, 25.64796309,  5.27822358, 16.34286454,
       38.44977079, 19.99080316, 19.04135707, 29.96991437,  1.20591082])

In [75]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))    #jeden neuron ponieważ bedziemy przewidywać ciągłą wwartość, nie dajemy tu f.  aktywacji

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Epoch 1/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 346.7891 - val_loss: 210.2468
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 208.3339 - val_loss: 210.5667
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 209.3842 - val_loss: 210.5113
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.2787 - val_loss: 212.3954
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 207.4291 - val_loss: 212.3425
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 208.2541 - val_loss: 211.7134
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 205.7487 - val_loss: 211.1734
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 207.4691 - val_loss: 211.4476
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205.0926 - val_loss: 213.0773
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204.4248 - val_loss: 212.4565
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205.8817 - val_loss: 212.1250
Epoch 12

In [76]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])  # średni błąd kwadratowy

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 15.5320 - mse: 358.2128 - val_loss: 12.6069 - val_mse: 210.3912
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4653 - mse: 208.6714 - val_loss: 12.6162 - val_mse: 210.7323
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5354 - mse: 211.2025 - val_loss: 12.6294 - val_mse: 211.3585
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.3789 - mse: 206.0491 - val_loss: 12.6240 - val_mse: 211.1153
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5277 - mse: 210.4082 - val_loss: 12.6460 - val_mse: 212.0844
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.4128 - mse: 208.2626 - val_loss: 12.6342 - val_mse: 211.3777
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.2367 - mse: 203.1853 - val_loss: 12.6674 - val_mse: 212.9787
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.4609 - mse: 209.7858 - val_loss: 12.6528 - val_mse: 212.1844
Epoch 9/

In [77]:
test_data = np.random.random((10, 150))

model.predict(test_data) # mamy dane które zostały przewidziane przez nasz model

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


array([[26.959394],
       [27.280407],
       [31.31908 ],
       [25.39785 ],
       [24.431293],
       [22.273476],
       [25.605148],
       [26.21546 ],
       [24.554382],
       [23.731562]], dtype=float32)